[project]
name = "voyager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "python-dotenv>=1.1.0",
    "pyyaml>=6.0.2",
    "slack-bolt>=1.23.0",
    "tqdm>=4.67.1",
]
